In [1]:
import torch

In [2]:
torch.tensor(9)

tensor(9)

In [3]:
revenue=torch.tensor([100,200,75,46])

In [4]:
revenue[1]

tensor(200)

In [5]:
q1 = torch.tensor([
    [200, 220, 250],  # Product A (iPhone)
    [150, 180, 210],  # Product B (iPad)
    [300, 330, 360]   # Product C (MacBook)
])

q2 = torch.tensor([
    [209, 231, 259],  # Product A (iPhone)
    [155, 192, 222],  # Product B (iPad)
    [310, 340, 375]   # Product C (MacBook)
])

In [6]:
q1+q2

tensor([[409, 451, 509],
        [305, 372, 432],
        [610, 670, 735]])

In [7]:
q2-q1


tensor([[ 9, 11,  9],
        [ 5, 12, 12],
        [10, 10, 15]])

In [8]:
q1*0.1

tensor([[20., 22., 25.],
        [15., 18., 21.],
        [30., 33., 36.]])

In [9]:
profit_per_unit = torch.tensor([
    [30,27,25],
    [20,18,17],
    [45,38,39]
])

In [10]:
q1*profit_per_unit

tensor([[ 6000,  5940,  6250],
        [ 3000,  3240,  3570],
        [13500, 12540, 14040]])

In [11]:
product_prices=torch.tensor([1100,450,1500])

In [12]:
product_prices*q1 #not the right way to do

tensor([[220000,  99000, 375000],
        [165000,  81000, 315000],
        [330000, 148500, 540000]])

In [13]:
torch.matmul(product_prices,q1)

tensor([737500, 818000, 909500])

In [15]:
product_prices=torch.tensor([[1100,450,1500]])

In [16]:
product_prices.t()

tensor([[1100],
        [ 450],
        [1500]])

In [17]:
prices_by_region = q1*product_prices.t()
prices_by_region

tensor([[220000, 242000, 275000],
        [ 67500,  81000,  94500],
        [450000, 495000, 540000]])

In [22]:
prices_by_region.sum(dim=0)

tensor([737500, 818000, 909500])

In [23]:
# Create portfolio composition matrix (3x3)
# Rows: Different portfolios (P1, P2, P3)
# Columns: Asset allocation (Stocks, Bonds, Real Estate)
portfolio_composition = torch.tensor([
    [100.0, 50.0, 30.0],  # P1
    [80.0, 70.0, 20.0],   # P2
    [60.0, 40.0, 90.0]    # P3
], dtype=torch.float32)

# Create price change matrix (3x3)
# Rows: Assets (Stocks, Bonds, Real Estate)
# Columns: Economic scenarios (Growth, Neutral, Recession)
price_changes = torch.tensor([
    [1.15, 1.05, 0.85],  # Stocks
    [1.05, 1.02, 1.10],  # Bonds
    [1.10, 1.00, 0.90]   # Real Estate
], dtype=torch.float32)

values = torch.matmul(portfolio_composition, price_changes)
values

tensor([[200.5000, 186.0000, 167.0000],
        [187.5000, 175.4000, 163.0000],
        [210.0000, 193.8000, 176.0000]])

In [24]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("Using GPU for large-scale customer data processing")
else:
    device = torch.device("cpu")
    print("Using CPU for customer data processing")

Using CPU for customer data processing


In [26]:
customers_data=torch.rand(1_000_000,3,device=device)

In [27]:
customers_data.size()

torch.Size([1000000, 3])

In [32]:
customers_data[:5]

tensor([[0.3116, 0.8339, 0.4009],
        [0.4553, 0.7339, 0.2535],
        [0.3746, 0.9272, 0.2575],
        [0.4968, 0.2488, 0.5262],
        [0.4453, 0.4096, 0.8775]])

In [29]:
customers_data[:,1]

tensor([0.8339, 0.7339, 0.9272,  ..., 0.0591, 0.7837, 0.6178])

In [34]:
selected=customers_data[customers_data[:,1]>0.5]

In [36]:
selected.shape

torch.Size([500814, 3])

In [37]:
selected = selected.to("cpu")

In [38]:
units = torch.tensor([
    [200, 220],  # Product A (iPhone)
    [150, 180],  # Product B (iPad)
    [300, 330]   # Product C (MacBook)
])

In [39]:
units.shape

torch.Size([3, 2])

In [41]:
units.dtype

torch.int64

In [42]:
units.device

device(type='cpu')

In [43]:
units.view(-1)

tensor([200, 220, 150, 180, 300, 330])

In [47]:
units.view(6,1)

tensor([[200],
        [220],
        [150],
        [180],
        [300],
        [330]])

In [48]:
units

tensor([[200, 220],
        [150, 180],
        [300, 330]])

In [49]:
units[0,1]=22

In [50]:
units

tensor([[200,  22],
        [150, 180],
        [300, 330]])

In [52]:
torch.rand(6,6)

tensor([[0.8051, 0.8334, 0.6208, 0.7537, 0.0731, 0.3090],
        [0.3487, 0.6094, 0.3029, 0.9863, 0.5813, 0.7380],
        [0.0993, 0.7711, 0.1859, 0.4836, 0.1583, 0.3585],
        [0.0977, 0.6878, 0.7485, 0.4804, 0.2616, 0.9347],
        [0.6182, 0.5980, 0.7065, 0.0556, 0.5223, 0.1618],
        [0.1733, 0.0730, 0.2894, 0.0376, 0.6033, 0.6531]])

In [54]:
torch.zeros(6,6)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [55]:
torch.ones(6,6)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])